{ config, lib, pkgs, ... }:

let
  cfg = config.services.hecate;
  daemonCfg = cfg.daemon;

  # Generate the .env file content
  envFileContent = lib.concatStringsSep "\n" ([
    "# Hecate Daemon Configuration"
    "# Generated by NixOS activation"
    ""
    "# Mesh"
    "HECATE_MESH_BOOTSTRAP=${cfg.mesh.bootstrap}"
    "HECATE_MESH_REALM=${cfg.mesh.realm}"
    ""
    "# API (Unix socket)"
    "HECATE_API_SOCKET=/data/sockets/api.sock"
    "HECATE_DATA_DIR=/data"
    ""
    "# LLM"
    "HECATE_LLM_BACKEND=${cfg.ollama.backend}"
    "HECATE_LLM_ENDPOINT=${cfg.ollama.endpoint}"
  ] ++ lib.optionals (cfg.cluster.enable) [
    ""
    "# BEAM Cluster"
    "HECATE_ERLANG_COOKIE=${cfg.cluster.cookie}"
    "HECATE_CLUSTER_PEERS=${lib.concatStringsSep "," cfg.cluster.peers}"
  ]);

  # Generate the .container file content
  containerFileContent = lib.concatStringsSep "\n" [
    "[Unit]"
    "Description=Hecate Daemon (core)"
    "After=network-online.target"
    "Wants=network-online.target"
    ""
    "[Container]"
    "Image=ghcr.io/hecate-social/hecate-daemon:${daemonCfg.version}"
    "ContainerName=hecate-daemon"
    "AutoUpdate=registry"
    "Network=host"
    "Volume=%h/.hecate/hecate-daemon:/data:Z"
    "EnvironmentFile=%h/.hecate/gitops/system/hecate-daemon.env"
    ""
    "# Health check: daemon socket presence"
    "HealthCmd=test -S /data/sockets/api.sock"
    "HealthInterval=30s"
    "HealthRetries=3"
    "HealthTimeout=5s"
    "HealthStartPeriod=15s"
    ""
    "[Service]"
    "Restart=on-failure"
    "RestartSec=10s"
    "TimeoutStartSec=120s"
    ""
    "[Install]"
    "WantedBy=default.target"
  ];

  # Pre-generate files in the Nix store, then copy during activation
  containerFile = pkgs.writeText "hecate-daemon.container" containerFileContent;
  envFile = pkgs.writeText "hecate-daemon.env" envFileContent;
in
{
  options.services.hecate.gitops = {
    seedDaemon = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Whether to seed gitops with daemon Quadlet files on activation.";
    };
  };

  config = lib.mkIf cfg.gitops.seedDaemon {
    # Write Quadlet files via activation script
    system.activationScripts.hecate-gitops = {
      text = ''
        install -d -m 0750 -o ${cfg.user} -g ${cfg.group} ${cfg.dataDir}/gitops/system

        install -m 0644 -o ${cfg.user} -g ${cfg.group} \
          ${containerFile} \
          ${cfg.dataDir}/gitops/system/hecate-daemon.container

        install -m 0640 -o ${cfg.user} -g ${cfg.group} \
          ${envFile} \
          ${cfg.dataDir}/gitops/system/hecate-daemon.env
      '';
      deps = [ "users" ];
    };
  };
}
