# -----------------------------------------------------
# General window decoration
# name: "Minimal with Blur"
# -----------------------------------------------------

decoration {
    rounding = 0
    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0

    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = on
        ignore_opacity = false
    }

    shadow {
        enabled = false
    }
}
